import type {
  Transaction,
  BehaviorProfile,
  NetworkAnalysis,
  SystemStatus,
  DailyRiskDataPoint,
  AmountDataPoint,
  HourlyDataPoint,
  DemoScenarioConfig,
} from './types';

// ─── Mock User ──────────────────────────────────────────────────────────────

export const MOCK_USER = {
  id: 'user_ayush_01',
  name: 'Ayush Sharma',
  upiId: 'ayush.sharma@okaxis',
  avatar: 'AS',
};

// ─── Mock Transactions ───────────────────────────────────────────────────────

export const MOCK_TRANSACTIONS: Transaction[] = [
  {
    id: 'TXN001',
    userId: 'user_ayush_01',
    amount: 250,
    recipient: 'canteen@upi',
    recipientName: 'College Canteen',
    timestamp: '2026-09-19T08:32:00+05:30',
    location: { city: 'Ludhiana', state: 'Punjab' },
    deviceId: 'dev_iphone_01',
    deviceName: 'iPhone 14 Pro',
    isNewDevice: false,
    isNewRecipient: false,
    message: 'Lunch',
    riskScore: 8,
    riskLevel: 'LOW',
    category: 'Food',
    status: 'completed',
    reasons: [],
  },
  {
    id: 'TXN002',
    userId: 'user_ayush_01',
    amount: 820,
    recipient: 'amazon.pay@upi',
    recipientName: 'Amazon',
    timestamp: '2026-09-19T10:15:00+05:30',
    location: { city: 'Ludhiana', state: 'Punjab' },
    deviceId: 'dev_iphone_01',
    deviceName: 'iPhone 14 Pro',
    isNewDevice: false,
    isNewRecipient: false,
    message: 'Order #AMZ-98732',
    riskScore: 12,
    riskLevel: 'LOW',
    category: 'Shopping',
    status: 'completed',
    reasons: [],
  },
  {
    id: 'TXN003',
    userId: 'user_ayush_01',
    amount: 450,
    recipient: 'rohan.k@okicici',
    recipientName: 'Rohan Kumar',
    timestamp: '2026-09-19T11:45:00+05:30',
    location: { city: 'Ludhiana', state: 'Punjab' },
    deviceId: 'dev_iphone_01',
    deviceName: 'iPhone 14 Pro',
    isNewDevice: false,
    isNewRecipient: false,
    message: 'Movie tickets',
    riskScore: 9,
    riskLevel: 'LOW',
    category: 'Entertainment',
    status: 'completed',
    reasons: [],
  },
  {
    id: 'TXN004',
    userId: 'user_ayush_01',
    amount: 1200,
    recipient: 'zomato@icici',
    recipientName: 'Zomato Restaurant',
    timestamp: '2026-09-18T19:30:00+05:30',
    location: { city: 'Ludhiana', state: 'Punjab' },
    deviceId: 'dev_iphone_01',
    deviceName: 'iPhone 14 Pro',
    isNewDevice: false,
    isNewRecipient: false,
    message: 'Family dinner',
    riskScore: 22,
    riskLevel: 'LOW',
    category: 'Food',
    status: 'completed',
    reasons: [
      {
        type: 'amount_elevated',
        severity: 'LOW',
        title: 'Amount slightly above average',
        description: 'This payment is higher than your typical transaction amount but within an acceptable range.',
        contribution: 22,
      },
    ],
  },
  {
    id: 'TXN005',
    userId: 'user_ayush_01',
    amount: 350,
    recipient: 'spotify.india@upi',
    recipientName: 'Spotify India',
    timestamp: '2026-09-18T09:00:00+05:30',
    location: { city: 'Ludhiana', state: 'Punjab' },
    deviceId: 'dev_iphone_01',
    deviceName: 'iPhone 14 Pro',
    isNewDevice: false,
    isNewRecipient: false,
    message: 'Monthly subscription',
    riskScore: 5,
    riskLevel: 'LOW',
    category: 'Subscription',
    status: 'completed',
    reasons: [],
  },
  {
    id: 'TXN006',
    userId: 'user_ayush_01',
    amount: 580,
    recipient: 'ola.cabs@paytm',
    recipientName: 'Ola Cabs',
    timestamp: '2026-09-17T17:20:00+05:30',
    location: { city: 'Chandigarh', state: 'Punjab' },
    deviceId: 'dev_iphone_01',
    deviceName: 'iPhone 14 Pro',
    isNewDevice: false,
    isNewRecipient: false,
    message: 'Ride to airport',
    riskScore: 18,
    riskLevel: 'LOW',
    category: 'Transport',
    status: 'completed',
    reasons: [],
  },
  {
    id: 'TXN007',
    userId: 'user_ayush_01',
    amount: 3200,
    recipient: 'priya.m@ybl',
    recipientName: 'Priya Mehta',
    timestamp: '2026-09-17T14:05:00+05:30',
    location: { city: 'Ludhiana', state: 'Punjab' },
    deviceId: 'dev_iphone_01',
    deviceName: 'iPhone 14 Pro',
    isNewDevice: false,
    isNewRecipient: false,
    message: 'Rent split',
    riskScore: 38,
    riskLevel: 'MEDIUM',
    category: 'Personal',
    status: 'completed',
    reasons: [
      {
        type: 'amount_elevated',
        severity: 'MEDIUM',
        title: 'Amount above typical range',
        description: 'This payment of ₹3,200 is above your typical range of ₹100–₹1,500.',
        contribution: 38,
      },
    ],
  },
  {
    id: 'TXN008',
    userId: 'user_ayush_01',
    amount: 48000,
    recipient: 'rahulent@upi',
    recipientName: 'Unknown Recipient',
    timestamp: '2026-09-16T23:15:00+05:30',
    location: { city: 'Mumbai', state: 'Maharashtra' },
    deviceId: 'dev_unknown_02',
    deviceName: 'Unknown Android Device',
    isNewDevice: true,
    isNewRecipient: true,
    message: 'Urgent KYC verification required. Pay ₹48,000 to reactivate your account.',
    riskScore: 91,
    riskLevel: 'HIGH',
    category: 'Unknown',
    status: 'blocked',
    reasons: [
      {
        type: 'amount_extreme',
        severity: 'HIGH',
        title: 'Amount is 18× higher than normal',
        description: 'This payment of ₹48,000 is significantly above your average transaction of ₹620.',
        technicalDetail: 'z-score: 14.2 | 98th percentile of your transaction history',
        contribution: 35,
      },
      {
        type: 'new_recipient',
        severity: 'HIGH',
        title: 'First-time recipient',
        description: 'You have never sent money to rahulent@upi before.',
        technicalDetail: 'Recipient not in known UPI ID history',
        contribution: 25,
      },
      {
        type: 'new_device',
        severity: 'HIGH',
        title: 'New device detected',
        description: 'This payment originated from a device that has never been associated with your account.',
        technicalDetail: 'Device fingerprint: unknown | Trust level: 0',
        contribution: 20,
      },
      {
        type: 'location_anomaly',
        severity: 'MEDIUM',
        title: 'Unusual location',
        description: 'Transaction originated from Mumbai, which is far from your typical activity in Punjab.',
        technicalDetail: 'Distance from usual area: ~1,900 km',
        contribution: 7,
      },
      {
        type: 'message_signal',
        severity: 'MEDIUM',
        title: 'Urgency & verification language detected',
        description: 'The payment message contains keywords associated with social engineering scams.',
        technicalDetail: 'Flags: urgency, kyc_reference, account_threat',
        contribution: 4,
      },
    ],
  },
  {
    id: 'TXN009',
    userId: 'user_ayush_01',
    amount: 199,
    recipient: 'netflix.india@upi',
    recipientName: 'Netflix India',
    timestamp: '2026-09-15T20:00:00+05:30',
    location: { city: 'Ludhiana', state: 'Punjab' },
    deviceId: 'dev_iphone_01',
    deviceName: 'iPhone 14 Pro',
    isNewDevice: false,
    isNewRecipient: false,
    message: 'Monthly plan',
    riskScore: 4,
    riskLevel: 'LOW',
    category: 'Subscription',
    status: 'completed',
    reasons: [],
  },
  {
    id: 'TXN010',
    userId: 'user_ayush_01',
    amount: 750,
    recipient: 'medplus.pharmacy@upi',
    recipientName: 'MedPlus Pharmacy',
    timestamp: '2026-09-14T11:30:00+05:30',
    location: { city: 'Ludhiana', state: 'Punjab' },
    deviceId: 'dev_iphone_01',
    deviceName: 'iPhone 14 Pro',
    isNewDevice: false,
    isNewRecipient: false,
    message: 'Medicine',
    riskScore: 10,
    riskLevel: 'LOW',
    category: 'Healthcare',
    status: 'completed',
    reasons: [],
  },
  {
    id: 'TXN011',
    userId: 'user_ayush_01',
    amount: 2800,
    recipient: 'unknown.vendor99@ybl',
    recipientName: 'Unknown Vendor',
    timestamp: '2026-09-13T16:45:00+05:30',
    location: { city: 'Delhi', state: 'Delhi' },
    deviceId: 'dev_iphone_01',
    deviceName: 'iPhone 14 Pro',
    isNewDevice: false,
    isNewRecipient: true,
    message: 'Invoice payment',
    riskScore: 55,
    riskLevel: 'MEDIUM',
    category: 'Business',
    status: 'completed',
    reasons: [
      {
        type: 'new_recipient',
        severity: 'MEDIUM',
        title: 'New recipient',
        description: 'This is your first payment to unknown.vendor99@ybl.',
        contribution: 25,
      },
      {
        type: 'location_anomaly',
        severity: 'MEDIUM',
        title: 'Unusual location',
        description: 'Transaction from Delhi, outside your usual area.',
        contribution: 20,
      },
      {
        type: 'amount_elevated',
        severity: 'LOW',
        title: 'Amount above typical range',
        description: 'Payment is above your typical range of ₹100–₹1,500.',
        contribution: 10,
      },
    ],
  },
];

// ─── Mock Behavior Profile ────────────────────────────────────────────────────

export const MOCK_BEHAVIOR_PROFILE: BehaviorProfile = {
  userId: 'user_ayush_01',
  averageAmount: 620,
  medianAmount: 420,
  typicalRange: { min: 100, max: 1500 },
  knownRecipients: 12,
  trustedDevices: 2,
  averageDailyTransactions: 5,
  commonLocations: ['Ludhiana, Punjab', 'Chandigarh, Punjab', 'Amritsar, Punjab'],
  peakHours: [9, 12, 19, 21],
  totalTransactions: 187,
  profileUpdatedAt: '2026-09-19T00:00:00+05:30',
};

// ─── Mock Network Analysis ────────────────────────────────────────────────────

export const MOCK_NETWORK_ANALYSIS: NetworkAnalysis = {
  nodes: [
    {
      id: 'acc_A',
      label: 'Account A',
      type: 'user',
      x: 150,
      y: 100,
      riskLevel: 'HIGH',
      transactionCount: 8,
      totalAmount: 96000,
    },
    {
      id: 'acc_B',
      label: 'Account B',
      type: 'user',
      x: 350,
      y: 80,
      riskLevel: 'HIGH',
      transactionCount: 12,
      totalAmount: 144000,
    },
    {
      id: 'acc_C',
      label: 'Account C',
      type: 'user',
      x: 100,
      y: 280,
      riskLevel: 'HIGH',
      transactionCount: 6,
      totalAmount: 72000,
    },
    {
      id: 'acc_D',
      label: 'Account D',
      type: 'user',
      x: 380,
      y: 290,
      riskLevel: 'MEDIUM',
      transactionCount: 5,
      totalAmount: 35000,
    },
    {
      id: 'acc_E',
      label: 'Account E',
      type: 'user',
      x: 240,
      y: 320,
      riskLevel: 'MEDIUM',
      transactionCount: 4,
      totalAmount: 28000,
    },
    {
      id: 'acc_X',
      label: 'Account X',
      type: 'suspicious',
      x: 250,
      y: 190,
      riskLevel: 'HIGH',
      transactionCount: 42,
      totalAmount: 504000,
    },
  ],
  edges: [
    { id: 'e1', source: 'acc_A', target: 'acc_X', amount: 12000, suspicious: true, timestamp: '2026-09-19T02:00:00Z' },
    { id: 'e2', source: 'acc_B', target: 'acc_X', amount: 18000, suspicious: true, timestamp: '2026-09-19T02:05:00Z' },
    { id: 'e3', source: 'acc_C', target: 'acc_X', amount: 9000, suspicious: true, timestamp: '2026-09-19T02:10:00Z' },
    { id: 'e4', source: 'acc_D', target: 'acc_X', amount: 7000, suspicious: true, timestamp: '2026-09-19T02:12:00Z' },
    { id: 'e5', source: 'acc_E', target: 'acc_X', amount: 5500, suspicious: true, timestamp: '2026-09-19T02:15:00Z' },
    { id: 'e6', source: 'acc_A', target: 'acc_B', amount: 2000, suspicious: false, timestamp: '2026-09-18T10:00:00Z' },
    { id: 'e7', source: 'acc_C', target: 'acc_D', amount: 1500, suspicious: false, timestamp: '2026-09-18T11:00:00Z' },
  ],
  riskLevel: 'HIGH',
  connectedAccounts: 5,
  transactionsAnalyzed: 42,
  suspiciousConnections: 7,
  patternDescription:
    'Multiple accounts are routing funds to a single destination (Account X) within a short time window. This pattern is consistent with coordinated fund aggregation.',
  clusterDescription:
    'Hub-and-spoke anomaly detected. Accounts A, B, C, D, and E show no prior relationship but all transacted with Account X within 15 minutes.',
};

// ─── Mock System Status ───────────────────────────────────────────────────────

export const MOCK_SYSTEM_STATUS: SystemStatus = {
  riskEngine: 'operational',
  behaviorModel: 'operational',
  database: 'connected',
  api: 'operational',
  modelVersion: 'v0.1.0',
  lastUpdated: '2026-09-19T02:46:00+05:30',
};

// ─── Mock 7-Day Risk Chart Data ───────────────────────────────────────────────

export const MOCK_DAILY_RISK_DATA: DailyRiskDataPoint[] = [
  { day: 'Mon', riskScore: 12, transactions: 4, amount: 1820 },
  { day: 'Tue', riskScore: 8, transactions: 6, amount: 3240 },
  { day: 'Wed', riskScore: 18, transactions: 5, amount: 2100 },
  { day: 'Thu', riskScore: 35, transactions: 7, amount: 5800 },
  { day: 'Fri', riskScore: 22, transactions: 5, amount: 2950 },
  { day: 'Sat', riskScore: 14, transactions: 4, amount: 1680 },
  { day: 'Sun', riskScore: 91, transactions: 7, amount: 52450 },
];

// ─── Mock Amount Distribution Data ───────────────────────────────────────────

export const MOCK_AMOUNT_DISTRIBUTION: AmountDataPoint[] = [
  { range: '₹0–200', count: 28 },
  { range: '₹200–500', count: 64 },
  { range: '₹500–1000', count: 48 },
  { range: '₹1k–2k', count: 22 },
  { range: '₹2k–5k', count: 14 },
  { range: '₹5k–10k', count: 7 },
  { range: '₹10k+', count: 4 },
];

// ─── Mock Hourly Activity Data ────────────────────────────────────────────────

export const MOCK_HOURLY_DATA: HourlyDataPoint[] = [
  { hour: '6AM', count: 2 },
  { hour: '7AM', count: 5 },
  { hour: '8AM', count: 8 },
  { hour: '9AM', count: 18 },
  { hour: '10AM', count: 12 },
  { hour: '11AM', count: 10 },
  { hour: '12PM', count: 22 },
  { hour: '1PM', count: 15 },
  { hour: '2PM', count: 9 },
  { hour: '3PM', count: 7 },
  { hour: '4PM', count: 6 },
  { hour: '5PM', count: 9 },
  { hour: '6PM', count: 11 },
  { hour: '7PM', count: 20 },
  { hour: '8PM', count: 18 },
  { hour: '9PM', count: 14 },
  { hour: '10PM', count: 8 },
  { hour: '11PM', count: 3 },
];

// ─── Demo Scenarios ───────────────────────────────────────────────────────────

export const DEMO_SCENARIOS: DemoScenarioConfig[] = [
  {
    id: 'normal',
    label: 'Normal Payment',
    description: 'Typical transaction consistent with user behavior',
    recipient: 'canteen@upi',
    amount: 350,
    message: 'Lunch',
    location: 'Ludhiana, Punjab',
    expectedRisk: 'LOW',
    expectedScore: 8,
  },
  {
    id: 'suspicious',
    label: 'Suspicious Payment',
    description: 'High-risk transaction with multiple anomaly signals',
    recipient: 'rahulent@upi',
    amount: 48000,
    message: 'Urgent KYC verification required. Pay immediately to reactivate your account.',
    location: 'Mumbai, Maharashtra',
    expectedRisk: 'HIGH',
    expectedScore: 91,
  },
  {
    id: 'coordinated',
    label: 'Coordinated Pattern',
    description: 'Network-level anomaly across connected accounts',
    recipient: 'hub.account.x@ybl',
    amount: 12000,
    message: 'Transfer',
    location: 'Delhi, Delhi',
    expectedRisk: 'HIGH',
    expectedScore: 78,
  },
];
